name: Run QA BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cucumber tests (JSON output)
        run: npm test

      - name: Upload JSON report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: reports/cucumber_report.json
          retention-days: 7